import { test, expect } from '@playwright/test';

test.use({
  serviceWorkers: 'block'
});

test('test', async ({ page }) => {
  await page.routeFromHAR('C:\\Users\\Charmain\\Downloads\\AI VS Code Folders -.-\\EAINT-11982 Application Expiry Extension\\preapp-flow.har');
  await page.goto('https://staging.eauto.my/obs/preOnb/recaptcha');
  await page.locator('iframe[name="a-wo62na4pd3vv"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="7"]').click();
  await page.locator('div:nth-child(3) > div').first().click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wo62na4pd3vv"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="a-wo62na4pd3vv"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
});