# https://staging.eauto.my/obs/admin/preOnb/summary/cd404c0b-8746-4bfb-9846-73edc6a0d187
- banner:
  - img "header-line"
  - img "Logo"
  - text: Dealer Application - P260831/00838 / - CHARMAIN QA11982 260831-1744-139 ENTERPRISE
- link "Pre-Application":
  - /url: "#"
- link "Application":
  - /url: /obs/admin/form/edit/69a88691-a3e7-4b65-9f75-6d80ae961de6
- text: Pre-Application Summary
- table:
  - rowgroup:
    - 'row "Pre-Application No: P260831/00838"':
      - cell "Pre-Application No:"
      - cell "P260831/00838"
    - 'row "Business Registered Name: CHARMAIN QA11982 260831-1744-139 ENTERPRISE"':
      - cell "Business Registered Name:"
      - cell "CHARMAIN QA11982 260831-1744-139 ENTERPRISE"
    - 'row "Business Trading License No: KCH/1744139"':
      - cell "Business Trading License No:"
      - cell "KCH/1744139"
    - 'row "Tax Identification No (TIN): C3117441390"':
      - cell "Tax Identification No (TIN):"
      - cell "C3117441390"
    - 'row "Showroom Address: LOT 12, JALAN QA, TAMAN AUTOMATION"':
      - cell "Showroom Address:"
      - cell "LOT 12, JALAN QA, TAMAN AUTOMATION"
    - 'row "Showroom Postcode: 93100"':
      - cell "Showroom Postcode:"
      - cell "93100"
    - 'row "State: SARAWAK"':
      - cell "State:"
      - cell "SARAWAK"
    - 'row "City: KUCHING"':
      - cell "City:"
      - cell "KUCHING"
    - 'row "Business Type: Business Trading (Sarawak)"':
      - cell "Business Type:"
      - cell "Business Trading (Sarawak)"
    - 'row "Trading License: Download trading-licence.pdf"':
      - cell "Trading License:"
      - cell "Download trading-licence.pdf":
        - button "Download trading-licence.pdf":
          - img "Download"
          - text: trading-licence.pdf
    - 'row "Pre-Application Fee: RM 108.00 (Inclusive of 8% Service Tax + Non-refundable) Please note that the Pre-Application payment is non-refundable."':
      - cell "Pre-Application Fee:"
      - cell "RM 108.00 (Inclusive of 8% Service Tax + Non-refundable) Please note that the Pre-Application payment is non-refundable."
- text: Payment Details
- table:
  - rowgroup:
    - 'row "Payment ID: P260831000879"':
      - cell "Payment ID:"
      - cell "P260831000879"
    - 'row "Payment Method: FPX Online Banking (Maybank)"':
      - cell "Payment Method:"
      - cell "FPX Online Banking (Maybank)"
    - 'row "Payment Date Time: 31-08-2026 05:45PM"':
      - cell "Payment Date Time:"
      - cell "31-08-2026 05:45PM"
    - 'row "Payment Status: Paid"':
      - cell "Payment Status:"
      - cell "Paid"
    - 'row "Payment Document: Download Invoice Invoice"':
      - cell "Payment Document:"
      - cell "Download Invoice Invoice":
        - button "Download Invoice Invoice":
          - img "Download Invoice"
          - text: Invoice
- text: Admin in Charge
- table:
  - rowgroup:
    - 'row "Name: QA ADMIN -"':
      - cell "Name:"
      - cell "QA ADMIN -"
    - 'row "Mobile No: 0126083117"':
      - cell "Mobile No:"
      - cell "0126083117"
    - 'row "Email Address: qa.eaint11982260831-1744-139@modefair.com We will email an invoice and/or e-invoice once payment is successful."':
      - cell "Email Address:"
      - cell "qa.eaint11982260831-1744-139@modefair.com We will email an invoice and/or e-invoice once payment is successful."
- text: "Pre-Application No: P260831/00838 Pre-Application Status: APPROVED Application Link:"
- textbox: https://staging.eauto.my/obs/form/a3c13510-2cb6-4279-a556-a95e684e092b?id=KCH%2F1744139&s=0435d069ead9bb9ea38923116c088296a892870528874c6668e4bd36473810f9&v=1
- button "Copy Link"
- text: "Pre-Application Submission Date: 31-08-2026 05:44PM Special Remarks:"
- textbox
- button "Update Special Remarks"
